name: Python CI/CD Workflow

on:
  workflow_dispatch:
  
permissions:
  contents: read
  id-token: write
  
jobs:
   terraform :
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
          python-version: '3.x'

    - name: Install Checkov
      run: |
          python -m pip install --upgrade pip
          pip install checkov

    - name: Run Checkov scan
      run: checkov -d .
      continue-on-error: true
      
    - name: Set up Go 1.20
      uses: actions/setup-go@v3
      with:
        go-version: '1.20'

    - name: Install Go dependencies
      run: |
        go mod tidy
        go mod vendor 

    - name: Set up AWS credentials using OIDC
      uses: aws-actions/configure-aws-credentials@v3
      with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}  
          aws-region: ${{ secrets.AWS_REGION }}  
          
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.4.0 

#    - name: Terraform Init
#      run: terraform init

    - name: Terraform Plan     
      run: |
        cd terraform
        terraform init
        terraform plan -out=tfplan

    - name: Run Terratest
      run: |
        go test -v terratest/test-terraform.go
 

    - name: Terraform Apply
      run: |
        cd terraform
        terraform apply -auto-approve tfplan
        
 #   - name: Run Destroy Script
  #    run: bash destroy.sh
